import type { TokenRenderer } from './token-renderer';
import type { TileRenderer } from './tile-renderer';
export declare function registerTokenRenderer(r: TokenRenderer): void;
export declare function registerTileRenderer(r: TileRenderer): void;
export declare function onCanvasReady(): void;
export declare function onCanvasTeardown(): void;
export declare function onSceneChange(scene: Scene, _changes: object): void;
export declare function onTileDraw(tile: Tile): void;
export declare function onTileRefresh(tile: Tile, flags?: Record<string, boolean>): void;
export declare function onTileFlagsChange(tile: Tile): void;
export declare function onTileSelect(tile: Tile): void;
export declare function onTileDeselect(tile: Tile): void;
export declare function onTileMove(_tile: Tile): void;
export declare function onTileDestroy(id: string): void;
export declare function onTokenDraw(token: Token): void;
export declare function onTokenRefresh(token: Token, flags?: Record<string, boolean>): void;
export declare function onTokenFlagsChange(token: Token): void;
export declare function onTokenSelect(token: Token): void;
export declare function onTokenDeselect(token: Token): void;
export declare function onTokenMove(_token: Token): void;
export declare function onTokenDestroy(id: string): void;
export declare function onSightRefresh(): void;
export declare function onGridConfigOpen(_app: Application): void;
export declare function onGridConfigClose(): void;
export declare function onGridConfigPreview(_params: object): void;
