declare const VIEW: "sw";
declare const FAMILY: "dimetric";
declare const ROOT: "modules/isoroll/test/e2e/assets/cabin";
declare const scene: any;
declare const manifest: any;
declare const result: any;
declare const actor: any;
declare const xs: any;
declare const ys: any;
