import "../styles/isoroll.scss";
import { registerVolumeSettings } from "./volume/settings";
import { VolumeOverlay } from "./volume/overlay";
import { VolumeGizmos } from "./volume/gizmos";
import { TokenOverlay } from "./volume/token-overlay";
import { TokenGizmos } from "./volume/token-gizmos";
import { TokenVolumeOverlay } from "./volume/token-volume-overlay";
import { TokenVolumeGizmos } from "./volume/token-volume-gizmos";
import { Occluder } from "./occluder/occluder";
import { CanvasTransform } from "./transform/canvas-transform";
import { BackgroundGizmos } from "./volume/background-gizmos";
import { ObjectTransform } from "./transform/object-transform";
import { registerSceneConfigHook, registerTileConfigHook, registerRulerPatch } from "./transform/scene-config";
import { registerTokenConfigHook } from "./ui/token-config";
import { PresetManager } from "./preset/preset-manager";
import { WallManager } from "./walls/wall-manager";

Hooks.once("init", () => {
  registerVolumeSettings();
  registerSceneConfigHook();
  registerTokenConfigHook();
  registerTileConfigHook();
  registerRulerPatch();
  CanvasTransform.activate();
  BackgroundGizmos.activate();
  ObjectTransform.activate();
  VolumeOverlay.activate();
  VolumeGizmos.activate();
  TokenOverlay.activate();
  TokenGizmos.activate();
  TokenVolumeOverlay.activate();
  TokenVolumeGizmos.activate();
  Occluder.activate();
  PresetManager.activate();
  WallManager.activate();
  console.log("isoroll | initialized");
});
